version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: ecommerce_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "15672:15672" # app connection
      - "5672:5672"   # management UI
    depends_on:
      - postgres

volumes:
  postgres_data: